export const qk = {
  me: ['me'] as const,
  dashboard: ['dashboard'] as const,
  topics: ['topics'] as const,
  topic: (id: string) => ['topic', id] as const,
  mentions: (filters: Record<string, string | undefined>) => ['mentions', filters] as const,
  connectors: ['connectors'] as const,
  webSearchStatus: ['web-search-status'] as const,
  ingestionJobs: ['ingestion-jobs'] as const,
  alertRules: ['alert-rules'] as const,
  alertEvents: ['alert-events'] as const,
  reports: ['reports'] as const,
  actors: ['actors'] as const,
  audit: ['audit'] as const,
  conversations: ['conversations'] as const,
  conversation: (id: string) => ['conversation', id] as const,
  timeseries: (topicId: string, bucket: string, days: number) => ['timeseries', topicId, bucket, days] as const,
  sentiment: (topicId: string) => ['sentiment', topicId] as const,
  platforms: (topicId: string) => ['platforms', topicId] as const,
  entities: (topicId: string) => ['entities', topicId] as const,
  insights: (topicId: string) => ['insights', topicId] as const,
  clusters: (topicId: string) => ['clusters', topicId] as const,
  riskEvents: (topicId: string) => ['risk-events', topicId] as const,
};
